bot_name: "Jon Snow the watcher"
icon_emoji: ":sleuth_or_spy:"
message_text: "Google Play Review:"
review_count: 20
location: "zh-tw"

# web_hook_uri: "your slack incoming hook"
# app_id: "com.streetvoice.streetvoice"
