bot_name: "Jon Snow the watcher"
icon_emoji: ":sleuth_or_spy:"
review_count: 20
google_play_location: "zh-tw"
app_store_location: "tw"

# web_hook_uri: "Your Slack incoming hooks"
# google_play_app_id: "com.streetvoice.streetvoice"
# app_store_app_id: "804704919"
